# -*- coding: utf-8 -*-
"""
guideline_to_sps.py - SPSS Syntax 자동 생성 도구 (범용)

변수 가이드라인 CSV 파일을 읽어 SPSS 25.0 syntax (.sps) 파일을 생성합니다.
- VARIABLE LABELS: 변수명과 설문 내용을 라벨로 지정
- VALUE LABELS: 각 변수의 값 라벨을 지정

사용법:
  python guideline_to_sps.py input.csv --output output_label.sps
  python guideline_to_sps.py input.csv --output out.sps --short-labels short.json --short-output out_short.sps
  python guideline_to_sps.py input.csv --output out.sps --encoding utf-8
"""

__version__ = "1.0.0"

import argparse
import csv
import json
import os
import sys


# ═══════════════════════════════════════════════════════════════
# 텍스트 정리
# ═══════════════════════════════════════════════════════════════

def clean_text(text: str) -> str:
    """SPSS 라벨용 텍스트 정리.

    - HTML entity 디코딩 (&amp; → &)
    - 줄바꿈 제거
    - CP949 비호환 특수문자 치환
    - 스마트 따옴표 → 일반 따옴표
    - SPSS 작은따옴표 이스케이프 (' → '')
    """
    text = text.replace("&amp;", "&")
    text = text.replace("\\n", " ")
    text = text.replace("\n", " ")
    # CP949 비호환 문자 치환
    text = text.replace("\uff65", "\u00b7")  # ･ → ·
    text = text.replace("\u2027", "\u00b7")  # ‧ → ·
    # 스마트 따옴표 → 일반 따옴표
    text = text.replace("\u2018", "'")   # '
    text = text.replace("\u2019", "'")   # '
    text = text.replace("\u201C", '"')   # "
    text = text.replace("\u201D", '"')   # "
    # SPSS 작은따옴표 이스케이프
    text = text.replace("'", "''")
    return text.strip()


# ═══════════════════════════════════════════════════════════════
# CSV 파싱
# ═══════════════════════════════════════════════════════════════

def parse_guideline(csv_path: str):
    """변수 가이드라인 CSV를 파싱하여 변수 라벨 및 값 라벨 목록을 반환.

    CSV 형식 (4컬럼):
      QtnType, 문항/보기번호, 내용, VALUE LABELS

    규칙:
      - QtnType이 있고 문항/보기번호가 변수명 → 변수 행
      - QtnType이 비어 있고 문항/보기번호가 숫자 → 값 라벨 행

    Returns:
        var_labels: [(var_name, label_text), ...]
        val_labels: [(var_name_expr, [(val, label), ...]), ...]
    """
    var_labels = []
    val_labels = []
    current_var = None
    current_values = []

    with open(csv_path, "r", encoding="utf-8-sig") as f:
        reader = csv.reader(f)
        header = next(reader)  # 헤더 스킵

        for row in reader:
            if len(row) < 3:
                continue

            qtn_type = row[0].strip()
            var_code = row[1].strip()
            content = row[2].strip()

            if qtn_type and var_code:
                # 새 변수 시작 → 이전 변수의 값 라벨 저장
                if current_var and current_values:
                    val_labels.append((current_var, current_values))
                current_var = var_code
                current_values = []
                # 변수 라벨 추가
                label_text = clean_text(content)
                if label_text:
                    var_labels.append((var_code, label_text))

            elif not qtn_type and var_code.isdigit() and content:
                # 값 라벨 행
                val_num = var_code
                val_text = clean_text(content)
                current_values.append((val_num, val_text))

        # 마지막 변수 처리
        if current_var and current_values:
            val_labels.append((current_var, current_values))

    return var_labels, val_labels


# ═══════════════════════════════════════════════════════════════
# SPS 생성
# ═══════════════════════════════════════════════════════════════

def generate_sps(var_labels, val_labels, output_path, *,
                 encoding="cp949", title=""):
    """SPSS syntax (.sps) 파일을 생성.

    Args:
        var_labels: [(var_name, label_text), ...]
        val_labels: [(var_name_expr, [(val, label), ...]), ...]
        output_path: 출력 파일 경로
        encoding: 출력 인코딩 ('cp949' 또는 'utf-8')
        title: SPS 파일 내 주석 제목
    """
    enc_label = "EUC-KR" if encoding == "cp949" else "UTF-8"
    lines = []

    # 헤더 주석
    lines.append(f"* Encoding: {enc_label}.")
    lines.append("* ============================================================.")
    if title:
        lines.append(f"* {title} - 변수 라벨 및 값 라벨.")
    lines.append("* SPSS 25.0 Syntax.")
    lines.append(f"* Generated by guideline_to_sps.py v{__version__}.")
    lines.append("* ============================================================.")
    lines.append("")

    # ── VARIABLE LABELS ──
    lines.append("* -- VARIABLE LABELS -----------------------------------------------.")
    lines.append("")
    lines.append("VARIABLE LABELS")

    for i, (var_name, label_text) in enumerate(var_labels):
        # TO 구문이 있는 경우 첫 번째 변수로만 라벨 지정
        display_name = var_name.split(" TO ")[0] if " TO " in var_name else var_name
        separator = "." if i == len(var_labels) - 1 else ""
        lines.append(f"   {display_name}  '{label_text}'{separator}")

    lines.append("EXECUTE.")
    lines.append("")

    # ── VALUE LABELS ──
    lines.append("* -- VALUE LABELS -------------------------------------------------.")
    lines.append("")
    lines.append("VALUE LABELS")

    for var_name, values in val_labels:
        lines.append(f"   /{var_name}")
        for val_num, val_text in values:
            lines.append(f"      {val_num}  '{val_text}'")

    lines.append(".")
    lines.append("EXECUTE.")
    lines.append("")

    # 파일 쓰기
    with open(output_path, "w", encoding=encoding) as f:
        f.write("\n".join(lines))

    return len(var_labels), len(val_labels)


# ═══════════════════════════════════════════════════════════════
# 간략 라벨 적용
# ═══════════════════════════════════════════════════════════════

def apply_short_labels(var_labels, short_labels_map):
    """변수 라벨 목록에 간략 라벨을 적용.

    Args:
        var_labels: [(var_name, original_label), ...]
        short_labels_map: {var_name: short_label, ...}

    Returns:
        [(var_name, short_or_original_label), ...]
    """
    result = []
    for var_name, original_label in var_labels:
        if var_name in short_labels_map:
            short_label = clean_text(short_labels_map[var_name])
            result.append((var_name, short_label))
        else:
            result.append((var_name, original_label))
    return result


# ═══════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════

def build_parser():
    parser = argparse.ArgumentParser(
        prog="guideline_to_sps",
        description="변수 가이드라인 CSV → SPSS 25.0 Syntax (.sps) 변환 도구",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
예시:
  python guideline_to_sps.py input.csv --output label.sps
  python guideline_to_sps.py input.csv -o label.sps --encoding utf-8
  python guideline_to_sps.py input.csv -o label.sps \\
         --short-labels short.json --short-output label_short.sps
        """,
    )
    parser.add_argument("input_csv", help="입력 가이드라인 CSV 파일 경로")
    parser.add_argument("-o", "--output", required=True,
                        help="원본 라벨 SPS 출력 경로")
    parser.add_argument("--encoding", default="cp949",
                        choices=["cp949", "utf-8"],
                        help="출력 인코딩 (기본: cp949)")
    parser.add_argument("--title", default="",
                        help="SPS 파일 내 주석 제목")
    parser.add_argument("--short-labels", default=None,
                        help="간략 라벨 JSON 파일 경로")
    parser.add_argument("--short-output", default=None,
                        help="간략 라벨 SPS 출력 경로")
    parser.add_argument("--version", action="version",
                        version=f"%(prog)s v{__version__}")
    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    # 입력 파일 확인
    if not os.path.isfile(args.input_csv):
        print(f"[오류] 입력 파일을 찾을 수 없습니다: {args.input_csv}",
              file=sys.stderr)
        sys.exit(1)

    # CSV 파싱
    print(f"[INFO] CSV 파싱 중: {args.input_csv}")
    var_labels, val_labels = parse_guideline(args.input_csv)
    print(f"       → 변수 라벨: {len(var_labels)}개, "
          f"값 라벨 변수: {len(val_labels)}개")

    # 원본 라벨 SPS 생성
    title = args.title or os.path.splitext(
        os.path.basename(args.input_csv))[0]
    n_var, n_val = generate_sps(
        var_labels, val_labels, args.output,
        encoding=args.encoding, title=title,
    )
    print(f"[완료] 원본 라벨 SPS 생성: {args.output}")
    print(f"       → 변수 라벨: {n_var}개, 값 라벨 변수: {n_val}개")

    # 간략 라벨 SPS 생성
    if args.short_labels and args.short_output:
        if not os.path.isfile(args.short_labels):
            print(f"[오류] 간략 라벨 파일을 찾을 수 없습니다: {args.short_labels}",
                  file=sys.stderr)
            sys.exit(1)

        with open(args.short_labels, "r", encoding="utf-8") as f:
            short_map = json.load(f)

        short_var_labels = apply_short_labels(var_labels, short_map)
        n_var_s, n_val_s = generate_sps(
            short_var_labels, val_labels, args.short_output,
            encoding=args.encoding, title=f"{title} (통계표용 간략)",
        )
        print(f"[완료] 간략 라벨 SPS 생성: {args.short_output}")
        print(f"       → 변수 라벨: {n_var_s}개, 값 라벨 변수: {n_val_s}개")

    elif args.short_labels and not args.short_output:
        print("[경고] --short-labels를 지정했으나 --short-output이 없습니다.",
              file=sys.stderr)

    print("[INFO] 작업 완료!")


if __name__ == "__main__":
    main()
